######################################################
#                                                    #
#        ╔╦╗╦ ╦╔═╗╔╦╗╦╔═╗  ╔═╗╦═╗╔═╗╔═╗╔═╗╔═╗        #
#        ║║║╚╦╝╚═╗ ║ ║║    ╠╣ ╠╦╝║╣ ║╣ ╔═╝║╣         #
#        ╩ ╩ ╩ ╚═╝ ╩ ╩╚═╝  ╚  ╩╚═╚═╝╚═╝╚═╝╚═╝        #
#                  Made by Ankh                      #
#                                                    #
#  This is my first plugin, so it may have bugs. If  #
#   you happen to find one, please report it here:   #
#           https://discord.gg/bU9ThrA               #
#                                                    #
######################################################

# Chat Message Feature. Enabled by default.
chat-options:
  enabled: true
  # Sets the frozen message interval, delay is measured in seconds.
  # This value must be an Integer (whole number).
  message-interval: 3
  # Message that is sent to the player on the interval set above.
  frozen-message: '&cYou were frozen by {staff}!'

# Chest GUI option. You can enable both GUI and Chat options if you so choose.
gui-options:
  enabled: false
  # This is where you set up how many rows, or slots, the menu will have. Each row is 9 item slots.
  # This must be a number between 1-9
  rows: 3
  # This sets the GUI menu header.
  menu-title: '&9Frozen!'
  # This is where you set up the items that appear in the inventory menu displayed to a player when frozen.
  # WARNING: Please keep in mind no two items should have the same name.
  items:
    item1:
      # You must use the minecraft material name for this option.
      # Example below.
      # material: 'golden_shovel'
      # WARNING: Item names may vary from version to version.
      material: 'stone'
      damage: 0
      amount: 1
      slots:
      - 13
      name: '&cFrozen!'
      lore:
      - '&cYou were frozen!'
    item2:
      material: 'stained_glass_pane'
      damage: 1
      amount: 16
      slots:
       - 12
       - 14
      name: 'Item 2'
      lore:
      - '&6Color Codes Supported!'
      - 'Line2'
     
# If neither option is enabled, players will still be frozen but it will not say anything to them.

# This is where you change the messages for commands and features.
# If you want to disable a message, set it to ''
# {player} displays the username of the player that is affected.
# {staff} displays the username of the player running the commands.
# These will only work in the messages they are shown in on the default config.
messages:
  # Prefix that appears before all freeze command messages.
  prefix: '&8[&bFreeze&8] &f'
  # Message that is sent to the player once they are un-frozen.
  unfrozen-message: '&aYou were unfrozen by {staff}!'
  # This is sent to the frozen player when they try to do something while frozen.
  deny-message: '&cYou cannot do that while frozen!'
  # This message is sent to a player when they attempt to attack a frozen player.
  attack-frozen: '&cYou cannot attack {player}, they are frozen!'
  # Sends a message to everyone with 'freeze.notify' when a player disconnects while frozen.
  frozen-leave: '&c&l{player} logged out while frozen!'
  # Messages for the /freeze command.
  freeze-command:
    success: '&a{player} was frozen!'
    no-args: '&cUsage: /freeze <player>'
    too-many-args: '&cToo Many Arguments!'
    player-not-found: '&cThere is no user online called {player}!'
    already-frozen: '&c{player} is already frozen!'
    player-exempt: '&cYou cannot freeze {player}!'
    no-permission: '&cYou don''t have permission to use the freeze command!'
  # Messages for the /unfreeze command.
  unfreeze-command:
    success: '&a{player} was un-frozen!'
    no-args: '&cUsage: /unfreeze <player>'
    too-many-args: '&cToo Many Arguments!'
    player-not-found: '&cThere is no user online called {player}!'
    not-frozen: '&c{player} is not frozen!'
    no-permission: '&cYou don''t have permission to use the unfreeze command!'
  # Messages for the /freload command.
  reload-command:
    success: '&cPlugin configuration reloaded.'
    no-permission: '&cYou don''t have permission to use the freload command!'
  notify:
    # These messages are shown to players with the 'freeze.notify' when a player is frozen or un-frozen.
    player-frozen: '&c{player} was frozen by {staff}.'
    player-unfrozen: '&c{player} was un-frozen by {staff}.'
    # Shown to players with 'freeze.reload.notify' when /freload is used.
    # This message will only appear if there are frozen players on reload.
    # When /freload is used, all frozen players are un-frozen.
    reload: '&cAll players un-frozen due to reload by {staff}.'
